# Generated by Django 3.1 on 2020-11-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('requests', models.PositiveBigIntegerField(default=0)),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cache_relation', to='environment.environment')),
            ],
            options={
                'verbose_name': 'cache',
                'verbose_name_plural': 'caches',
                'db_table': 'core_cache',
                'ordering': ['-requests'],
                'abstract': False,
                'unique_together': {('environment', 'name')},
            },
        ),
    ]
