# Generated by Django 4.0.7 on 2022-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
