# Generated by Django 3.2.5 on 2021-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='name',
            field=models.CharField(editable=False, max_length=2000),
        ),
    ]
