#!/usr/bin/env bash
#-------------------------------------------------------------------------------
set -e

SCRIPT_DIR="$(cd "$(dirname "$([ `readlink "$0"` ] && echo "`readlink "$0"`" || echo "$0")")"; pwd -P)"

ZIMAGI_DEFAULT_RUNTIME_REPO="${ZIMAGI_DEFAULT_RUNTIME_REPO:-registry.hub.docker.com}"
ZIMAGI_DEFAULT_RUNTIME_IMAGE="${ZIMAGI_DEFAULT_RUNTIME_IMAGE:-zimagi/zimagi:latest}"
#-------------------------------------------------------------------------------

if [ -f "${SCRIPT_DIR}/data/zimagi.env" ]
then
    source "${SCRIPT_DIR}/data/zimagi.env"
else
    ZIMAGI_REPO="${ZIMAGI_DEFAULT_RUNTIME_REPO}"
    ZIMAGI_IMAGE="${ZIMAGI_DEFAULT_RUNTIME_IMAGE}"
fi

if ! docker inspect "${ZIMAGI_IMAGE}" >/dev/null 2>&1
then
    rm -f "${SCRIPT_DIR}/data/zimagi.env"
    ZIMAGI_IMAGE="${ZIMAGI_DEFAULT_RUNTIME_IMAGE}"
fi
docker run --rm --interactive --tty \
    --env-file "${SCRIPT_DIR}/.env" \
    --env-file <(env | grep "ZIMAGI_") \
    --network host \
    --gpus all \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "${SCRIPT_DIR}/app:/usr/local/share/zimagi" \
    --volume "${SCRIPT_DIR}/data:/var/local/zimagi" \
    --volume "${SCRIPT_DIR}/lib:/usr/local/lib/zimagi" \
    "${ZIMAGI_IMAGE}" "${@}"
