#!/usr/bin/env bash
#
# Usage:
#
#  zimagi <command> [args] [flags/options]
#
#=========================================================================================
# Environment
#

export __zimagi_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export __zimagi_base="$(basename ${BASH_SOURCE[0]})"
export __zimagi_script_dir="${__zimagi_dir}/scripts"

source "${__zimagi_script_dir}/variables.sh"

for file in "${__zimagi_script_dir}/utilities"/*.sh; do
  source "$file"
done

import_environment
docker_runtime_image

#
#=========================================================================================
# Execution
#

$ZIMAGI_DOCKER_EXECUTABLE run --rm --interactive --tty \
   --env "ZIMAGI_CLI_EXEC=True" \
   --env-file <(env | grep "ZIMAGI_") \
   --network host \
   --volume /var/run/docker.sock:/var/run/docker.sock \
   --volume "${ZIMAGI_HOST_APP_DIR}:/usr/local/share/zimagi" \
   --volume "${ZIMAGI_HOST_DATA_DIR}:/var/local/zimagi" \
   --volume "${ZIMAGI_HOST_LIB_DIR}:/usr/local/lib/zimagi" \
   "$ZIMAGI_RUNTIME_IMAGE" "${@}"
