# Generated by Django 2.1.3 on 2018-11-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ssh_ip', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='environment.Environment')),
                ('groups', models.ManyToManyField(blank=True, related_name='servers', to='server.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('environment', 'name')},
        ),
    ]
