# Generated by Django 2.1.3 on 2018-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
