# Generated by Django 2.1.3 on 2019-02-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='server',
            name='firewalls',
            field=models.ManyToManyField(related_name='_server_firewalls_+', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(related_name='_server_groups_+', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='server',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subnet.Subnet'),
        ),
    ]
