# Generated by Django 2.1.3 on 2018-12-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20181124_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_ip',
        ),
        migrations.AddField(
            model_name='server',
            name='config',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='data_device',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='private_key',
            field=models.TextField(null=True),
        ),
    ]
