# Generated by Django 2.1.3 on 2019-03-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190224_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='server',
            name='firewalls',
            field=models.ManyToManyField(related_name='server_relation', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(related_name='server_relation', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='server',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_relation', to='subnet.Subnet'),
        ),
    ]
