# Generated by Django 2.1.3 on 2018-12-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20181218_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='servers', to='server.ServerGroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
