# Generated by Django 2.1.3 on 2018-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20181218_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='user',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
