# Generated by Django 2.1.3 on 2019-01-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20181229_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='servergroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ServerGroup'),
        ),
    ]
