# Generated by Django 2.1.3 on 2019-01-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_servergroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servergroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.ServerGroup'),
        ),
    ]
