# Generated by Django 2.1.3 on 2019-01-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190102_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='zone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
