# Generated by Django 2.1.3 on 2019-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190109_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='backup_device',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
