# Generated by Django 2.1.3 on 2019-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_server_backup_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='config',
        ),
        migrations.AddField(
            model_name='server',
            name='_config',
            field=models.TextField(db_column='config', null=True),
        ),
    ]
