# Generated by Django 2.1.3 on 2019-01-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20190126_1116'),
        ('server', '0010_auto_20190119_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='region',
        ),
        migrations.RemoveField(
            model_name='server',
            name='zone',
        ),
        migrations.AddField(
            model_name='server',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='network.Subnet'),
        ),
    ]
