# Generated by Django 2.1.3 on 2019-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190127_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='firewalls',
            field=models.ManyToManyField(related_name='servers', to='network.Firewall'),
        ),
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(related_name='servers', to='server.ServerGroup'),
        ),
    ]
