# Generated by Django 2.1.3 on 2019-02-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20190127_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
    ]
