# Generated by Django 2.1.3 on 2019-02-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systems.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0017_server__variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='ip',
            new_name='private_ip',
        ),
        migrations.AddField(
            model_name='server',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='public_ip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='firewalls',
            field=models.ManyToManyField(to='network.Firewall'),
        ),
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(to='server.ServerGroup'),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=systems.models.EncryptedCharField(max_length=1096, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='private_key',
            field=systems.models.EncryptedTextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='server',
            name='_config',
        ),
        migrations.RemoveField(
            model_name='server',
            name='_state_config',
        ),
        migrations.RemoveField(
            model_name='server',
            name='_variables',
        ),
        migrations.RemoveField(
            model_name='server',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='server',
            name='subnet',
        ),
        migrations.RemoveField(
            model_name='server',
            name='type',
        ),
    ]
