# Generated by Django 2.1.3 on 2019-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(to='group.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
