# Generated by Django 4.1.13 on 2025-05-14 05:10

import data.user.models
from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("config", systems.models.fields.DictionaryField(default=dict)),
                ("provider_type", models.CharField(default="base", max_length=128)),
                (
                    "variables",
                    systems.models.fields.DictionaryField(default=dict, editable=False),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("last_name", models.CharField(max_length=150, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "password",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                ("encryption_key", models.CharField(max_length=256, null=True)),
                ("last_login", models.DateTimeField(editable=False, null=True)),
                (
                    "groups",
                    models.ManyToManyField(blank=True, related_name="%(data_name)s", to="group.group"),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "core_user",
                "ordering": ["name"],
                "abstract": False,
            },
            managers=[
                ("objects", data.user.models.UserManager()),
            ],
        ),
    ]
