# Generated by Django 5.2.1 on 2025-05-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_token",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="temp_token_time",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
