# Generated by Django 2.1.3 on 2018-12-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('user', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('authtoken.token',),
        ),
    ]
