# Generated by Django 3.0 on 2020-02-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190406_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
    ]
