# Generated by Django 3.0 on 2020-02-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200208_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(editable=False, max_length=254, unique=True),
        ),
    ]
