# Generated by Django 4.1.13 on 2025-04-20 05:07

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_token",
            field=systems.models.fields.EncryptedCharField(
                editable=False, max_length=256, null=True
            ),
        ),
    ]
