# Generated by Django 4.1.13 on 2025-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_temp_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_token_time",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
