# Generated by Django 4.1.2 on 2022-10-28 00:28

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='secrets',
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='args',
            field=systems.models.fields.ListField(default=list),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='kwargs',
            field=systems.models.fields.DictionaryField(default=dict),
        ),
    ]
