# Generated by Django 3.0 on 2020-02-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'verbose_name': 'scheduled task', 'verbose_name_plural': 'scheduled tasks'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtaskchanges',
            options={'verbose_name': 'scheduled task change', 'verbose_name_plural': 'scheduled task changes'},
        ),
        migrations.AlterModelOptions(
            name='taskcrontab',
            options={'verbose_name': 'task crontab', 'verbose_name_plural': 'task crontabs'},
        ),
        migrations.AlterModelOptions(
            name='taskdatetime',
            options={'verbose_name': 'task datetime', 'verbose_name_plural': 'task datetimes'},
        ),
        migrations.AlterModelOptions(
            name='taskinterval',
            options={'verbose_name': 'task interval', 'verbose_name_plural': 'task intervals'},
        ),
    ]
