# Generated by Django 3.0 on 2020-02-02 05:14

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200201_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='args',
            field=systems.models.fields.EncryptedDataField(default='[]'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='kwargs',
            field=systems.models.fields.EncryptedDataField(default='{}'),
        ),
    ]
