# Generated by Django 4.0.1 on 2022-01-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20220102_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='clocked',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relation', to='schedule.taskdatetime'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='crontab',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relation', to='schedule.taskcrontab'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='interval',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relation', to='schedule.taskinterval'),
        ),
    ]
