# Generated by Django 4.0.6 on 2022-07-16 04:03

from django.db import migrations
import django_celery_beat.models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduledtask_clocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcrontab',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=django_celery_beat.models.crontab_schedule_celery_timezone, help_text='Timezone to Run the Cron Schedule on. Default is UTC.', use_pytz=False, verbose_name='Cron Timezone'),
        ),
    ]
