# Generated by Django 3.0 on 2020-05-19 11:29

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
        ('schedule', '0004_scheduledtask_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['name'], 'verbose_name': 'scheduled task', 'verbose_name_plural': 'scheduled tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskcrontab',
            options={'ordering': ['name'], 'verbose_name': 'task crontab', 'verbose_name_plural': 'task crontabs'},
        ),
        migrations.AlterModelOptions(
            name='taskdatetime',
            options={'ordering': ['name'], 'verbose_name': 'task datetime', 'verbose_name_plural': 'task datetimes'},
        ),
        migrations.AlterModelOptions(
            name='taskinterval',
            options={'ordering': ['name'], 'verbose_name': 'task interval', 'verbose_name_plural': 'task intervals'},
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='args',
            field=systems.models.fields.EncryptedDataField(default=[]),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='clocked',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduledtask_relation', to='schedule.TaskDatetime'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='crontab',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduledtask_relation', to='schedule.TaskCrontab'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='interval',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduledtask_relation', to='schedule.TaskInterval'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='kwargs',
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtask',
            unique_together={('environment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcrontab',
            unique_together={('environment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdatetime',
            unique_together={('environment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskinterval',
            unique_together={('environment', 'name')},
        ),
    ]
