# Generated by Django 4.0.7 on 2022-09-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_config_alter_user_groups_and_more'),
        ('schedule', '0005_alter_taskcrontab_name_alter_taskdatetime_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='clocked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.taskdatetime'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='crontab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.taskcrontab'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.taskinterval'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='user.user'),
        ),
        migrations.AlterField(
            model_name='taskcrontab',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskdatetime',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskinterval',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
