# Generated by Django 3.0 on 2020-06-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200519_0729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcrontab',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskdatetime',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskinterval',
            unique_together=set(),
        ),
    ]
