# Generated by Django 4.1.2 on 2022-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_scheduledtask_clocked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['created'], 'verbose_name': 'scheduled task', 'verbose_name_plural': 'scheduled tasks'},
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='id',
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
