# Generated by Django 3.1 on 2020-11-08 07:18

from django.db import migrations
import django_celery_beat.models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200615_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdatetime',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='taskcrontab',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=django_celery_beat.models.crontab_schedule_celery_timezone, help_text='Timezone to Run the Cron Schedule on. Default is UTC.', verbose_name='Cron Timezone'),
        ),
    ]
