# Generated by Django 2.1.3 on 2019-01-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0013_remove_environment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('_config', models.TextField(db_column='config', null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='environment.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('cidr', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(max_length=128, null=True)),
                ('_config', models.TextField(db_column='config', null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='environment.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('cidr', models.CharField(max_length=128, null=True)),
                ('_config', models.TextField(db_column='config', null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='environment.Environment')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='network.Network')),
            ],
        ),
        migrations.AddField(
            model_name='firewall',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='network.Network'),
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together={('network', 'name'), ('environment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('environment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='firewall',
            unique_together={('network', 'name'), ('environment', 'name')},
        ),
    ]
