# Generated by Django 2.1.3 on 2019-01-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('ingress', 'ingress'), ('egress', 'egress')], max_length=10)),
                ('from_port', models.IntegerField(null=True)),
                ('to_port', models.IntegerField(null=True)),
                ('protocol', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], default='tcp', max_length=10)),
                ('_cidrs', models.TextField(db_column='cidrs', null=True)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='network.Firewall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
