# Generated by Django 2.1.3 on 2019-03-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_network_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_relation', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='network',
            name='groups',
            field=models.ManyToManyField(related_name='network_relation', to='group.Group'),
        ),
    ]
