# Generated by Django 2.1.3 on 2019-01-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_firewallrule__config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firewall',
            unique_together={('network', 'name')},
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='environment',
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together={('network', 'name')},
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='environment',
        )
    ]
