# Generated by Django 2.1.3 on 2019-01-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20190126_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firewalls', to='network.Network'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='network.Firewall'),
        ),
        migrations.AlterField(
            model_name='network',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subnets', to='network.Network'),
        ),
    ]
