# Generated by Django 2.1.3 on 2019-02-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20190127_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
    ]
