# Generated by Django 2.1.3 on 2019-02-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20190202_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='_state',
        ),
        migrations.RemoveField(
            model_name='firewallrule',
            name='_state',
        ),
        migrations.RemoveField(
            model_name='network',
            name='_state',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='_state',
        ),
        migrations.AddField(
            model_name='firewall',
            name='_state_config',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='_state_config',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='_state_config',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='_state_config',
            field=models.TextField(db_column='state', null=True),
        ),
    ]
