# Generated by Django 2.1.3 on 2019-02-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20190202_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='mode',
            field=models.CharField(choices=[('ingress', 'ingress'), ('egress', 'egress')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='_config',
            field=models.TextField(db_column='config', default='{}'),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='_state_config',
            field=models.TextField(db_column='state', default='{}'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='_config',
            field=models.TextField(db_column='config', default='{}'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='_state_config',
            field=models.TextField(db_column='state', default='{}'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='_config',
            field=models.TextField(db_column='config', default='{}'),
        ),
        migrations.AlterField(
            model_name='network',
            name='_state_config',
            field=models.TextField(db_column='state', default='{}'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='_config',
            field=models.TextField(db_column='config', default='{}'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='_state_config',
            field=models.TextField(db_column='state', default='{}'),
        ),
    ]
