# Generated by Django 2.1.3 on 2019-02-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20190205_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='peers',
            field=models.ManyToManyField(to='network.Network'),
        ),
    ]
