# Generated by Django 2.1.3 on 2019-02-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0013_remove_environment_user'),
        ('network', '0011_network_peers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('_config', models.TextField(db_column='config', default='{}')),
                ('_variables', models.TextField(db_column='variables', default='{}')),
                ('_state_config', models.TextField(db_column='state', default='{}')),
                ('name', models.CharField(max_length=128)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_peers', to='environment.Environment')),
            ],
        ),
        migrations.RemoveField(
            model_name='network',
            name='peers',
        ),
        migrations.AddField(
            model_name='networkpeer',
            name='peers',
            field=models.ManyToManyField(to='network.Network'),
        ),
        migrations.AlterUniqueTogether(
            name='networkpeer',
            unique_together={('environment', 'name')},
        ),
    ]
