# Generated by Django 2.1.3 on 2019-02-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20190215_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkpeer',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
