# Generated by Django 5.2.1 on 2025-05-19 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_user_temp_token_user_temp_token_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(data_name)s",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat",
                "verbose_name_plural": "chats",
                "db_table": "core_chat",
                "ordering": ["user", "name", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(default="user", max_length=32)),
                ("content", models.TextField(default="")),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "db_table": "core_chat_message",
                "ordering": ["chat_id", "-created"],
                "abstract": False,
            },
        ),
    ]
