# Generated by Django 4.1.13 on 2025-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(default="system", max_length=32),
        ),
    ]
