# Generated by Django 4.1.13 on 2025-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="text",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="type",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(default="user", max_length=32),
        ),
    ]
