# Generated by Django 2.1.3 on 2019-01-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0011_auto_20181229_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=128, null=True)),
                ('config', models.TextField(null=True)),
                ('remote', models.CharField(max_length=256, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='environment.Environment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('environment', 'name')},
        ),
    ]
