# Generated by Django 2.1.3 on 2019-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='path',
        ),
    ]
