# Generated by Django 2.1.3 on 2019-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190224_1023'),
        ('project', '0002_auto_20190224_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(related_name='_project_groups_+', to='group.Group'),
        ),
    ]
