# Generated by Django 2.1.3 on 2019-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reference',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
