# Generated by Django 2.1.3 on 2019-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='config',
        ),
        migrations.AddField(
            model_name='project',
            name='_config',
            field=models.TextField(db_column='config', null=True),
        ),
    ]
