# Generated by Django 4.1.13 on 2025-05-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScalingEvent",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("worker_max_count", models.IntegerField(null=True)),
                ("worker_count", models.IntegerField(null=True)),
                ("task_count", models.IntegerField(null=True)),
                ("workers_created", models.IntegerField(null=True)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="log.log",
                    ),
                ),
            ],
            options={
                "verbose_name": "scaling event",
                "verbose_name_plural": "scaling events",
                "db_table": "core_scaling_event",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
