# Generated by Django 4.1.13 on 2025-05-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScalingEvent",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("command", models.CharField(max_length=255)),
                ("worker_type", models.CharField(max_length=255)),
                ("worker_max_count", models.IntegerField(null=True)),
                ("worker_count", models.IntegerField(null=True)),
                ("task_count", models.IntegerField(null=True)),
                ("workers_created", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "scaling event",
                "verbose_name_plural": "scaling events",
                "db_table": "core_scaling_event",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
