#
# Autogenerated tokens
#
resource "random_password" "argocd_server_secret" {
  length           = 20
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "random_password" "zimagi_secret_key" {
  length           = 20
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

#
# Passwords
#
resource "random_password" "zimagi_postgresql_password" {
  length  = 15
  special = false
}

resource "random_password" "zimagi_redis_password" {
  length  = 15
  special = false
}

resource "random_password" "zimagi_qdrant_password" {
  length  = 15
  special = false
}

#
# Application interpolation variables
#
locals {
  variables = sensitive({
    github_org            = var.github_org
    github_deployer_token = var.github_deployer_token

    argocd_server_secret  = random_password.argocd_server_secret.result
    argocd_admin_password = var.argocd_admin_password

    gateway_node_port = var.gateway_node_port
    certificate_key   = var.ssl_private_key
    certificate_cert  = var.ssl_certificate

    zimagi_postgresql_password = random_password.zimagi_postgresql_password.result
    zimagi_redis_password      = random_password.zimagi_redis_password.result
    zimagi_qdrant_password     = random_password.zimagi_qdrant_password.result

    zimagi_tag                 = var.zimagi_tag
    zimagi_os_password         = var.zimagi_os_password
    zimagi_secret_key          = random_password.zimagi_secret_key.result
    zimagi_admin_api_key       = var.zimagi_admin_api_key
    zimagi_email_host_user     = var.zimagi_email_host_user
    zimagi_email_host_password = var.zimagi_email_host_password
  })
}
