#!/usr/bin/env python3
import os
import sys

if __name__ == "__main__":
    from systems.command import execute_from_command_line
        
    args = sys.argv
    
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "services.cli.settings")
    execute_from_command_line(args)