# Generated by Django 2.1.3 on 2019-03-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190224_1023'),
        ('firewall', '0002_auto_20190224_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='groups',
            field=models.ManyToManyField(related_name='_firewall_groups_+', to='group.Group'),
        ),
    ]
