# Generated by Django 2.1.3 on 2019-03-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0003_firewall_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='groups',
            field=models.ManyToManyField(related_name='firewall_relation', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firewall_relation', to='network.Network'),
        ),
    ]
