# Generated by Django 2.1.3 on 2019-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190224_1023'),
        ('subnet', '0002_auto_20190224_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='groups',
            field=models.ManyToManyField(related_name='_subnet_groups_+', to='group.Group'),
        ),
    ]
