# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('command', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=64, null=True)),
                ('messages', systems.models.fields.EncryptedDataField(default=[])),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_relation', to='environment.Environment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.User')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'db_table': 'core_log',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('environment', 'name')},
        ),
    ]
