# Generated by Django 2.1.3 on 2019-02-25 21:14

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0003_auto_20190224_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('config', systems.models.fields.EncryptedDataField(default={})),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('user', models.CharField(max_length=150, null=True)),
                ('command', models.CharField(max_length=256, null=True)),
                ('messages', systems.models.fields.EncryptedDataField(default=[])),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='environment.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('environment', 'name')},
        ),
    ]
