# Generated by Django 2.1.7 on 2019-04-02 00:43

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created'], 'verbose_name': 'log', 'verbose_name_plural': 'logs'},
        ),
        migrations.AlterField(
            model_name='log',
            name='config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='environment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_relation', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
