# Generated by Django 4.0.7 on 2022-09-04 20:17

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_log_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='config',
            field=systems.models.fields.DictionaryField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
