# Generated by Django 2.1.3 on 2019-03-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_relation', to='environment.Environment'),
        ),
    ]
