# Generated by Django 3.0 on 2020-01-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20190703_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='task_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
