# Generated by Django 4.0.7 on 2022-09-26 08:38

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_log_config_alter_log_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='config',
            field=systems.models.fields.DictionaryField(default=dict),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
