# Generated by Django 4.1.2 on 2022-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_log_config_alter_log_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='scheduled',
        ),
        migrations.AddField(
            model_name='log',
            name='schedule',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='worker',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
