# Generated by Django 3.0 on 2020-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200128_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmessage',
            options={'ordering': ['-created'], 'verbose_name': 'log message', 'verbose_name_plural': 'log messages'},
        ),
        migrations.AddField(
            model_name='logmessage',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='logmessage',
            table='core_log_message',
        ),
    ]
