# Generated by Django 3.2.4 on 2021-07-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20200519_0729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='log',
            name='environment',
        ),
    ]
