# Generated by Django 2.1.7 on 2019-04-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'state', 'verbose_name_plural': 'states'},
        ),
        migrations.AlterField(
            model_name='state',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='environment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_relation', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
