# Generated by Django 4.1.2 on 2022-10-26 05:51

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('config', systems.models.fields.DictionaryField(default=dict)),
                ('provider_type', models.CharField(default='base', max_length=128)),
                ('secrets', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('variables', systems.models.fields.DictionaryField(default=dict, editable=False)),
                ('remote', models.CharField(max_length=256, null=True)),
                ('reference', models.CharField(max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='%(data_name)s', to='group.group')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'db_table': 'core_module',
                'ordering': ['-provider_type', 'name'],
                'abstract': False,
            },
        ),
    ]
