# Generated by Django 3.2.5 on 2021-07-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
        ('module', '0003_auto_20210711_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='environment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_relation', to='environment.environment'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('environment', 'name')},
        ),
    ]
