# Generated by Django 3.2.5 on 2021-07-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20210711_0417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='environment',
        ),
    ]
