# Generated by Django 4.1.7 on 2023-02-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='compatibility',
        ),
        migrations.RemoveField(
            model_name='module',
            name='version',
        ),
    ]
