# Generated by Django 2.1.3 on 2019-02-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systems.models.environment
import systems.models.provider


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0014_auto_20190221_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('networks', models.ManyToManyField(to='network.Network')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(systems.models.provider.ProviderMixin, systems.models.environment.EnvironmentMixin, models.Model),
        ),
    ]
