
DEFAULT_HOST = 'localhost'
DEFAULT_COMMAND_PORT = 5123
DEFAULT_DATA_PORT = 5323
DEFAULT_VERIFY_CERT = False

DEFAULT_USER = 'admin'
DEFAULT_TOKEN = 'uy5c8xiahf93j2pl8s00e6nb32h87dn3'

CONNECTION_RETRIES = 20
CONNECTION_RETRY_WAIT = 3

COMMAND_RAISE_ERROR = False

PARALLEL = True
THREAD_COUNT = 5

LOG_LEVEL = 'WARNING'
