#!/usr/bin/env bash
#
# Usage:
#
#  zimagi <command> [args] [flags/options]
#
#=========================================================================================
# Environment
#

export __zimagi_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export __zimagi_base="$(basename ${BASH_SOURCE[0]})"
export __zimagi_dir="$(dirname "${__zimagi_script_dir}")"

source "${__zimagi_script_dir}/variables.sh"

for file in "${__zimagi_script_dir}/utilities"/*.sh; do
  source "$file"
done

import_environment
docker_runtime_image

#
#=========================================================================================
# Execution
#
ZIMAGI_ARGS=(
  "--rm"
  "--interactive"
  "--tty"
  "--network" "host"
  "--user" "zimagi:$(stat -c '%g' /var/run/docker.sock)"
  "--volume" "/var/run/docker.sock:/var/run/docker.sock"
  "--volume" "${ZIMAGI_HOST_APP_DIR}:/usr/local/share/zimagi"
  "--volume" "${ZIMAGI_HOST_LIB_DIR}:/usr/local/lib/zimagi"
  "--volume" "${ZIMAGI_HOST_DATA_DIR}:/var/local/zimagi"
  "--env" "ZIMAGI_CLI_EXEC=True"
)
while IFS= read -r variable; do
  ZIMAGI_ARGS=("${ZIMAGI_ARGS[@]}" "--env" "$variable")
done <<< "$(env | grep -Po "ZIMAGI_[_A-Z0-9]+")"

ZIMAGI_ARGS=("${ZIMAGI_ARGS[@]}" "$ZIMAGI_RUNTIME_IMAGE" "${@}")
$ZIMAGI_DOCKER_EXECUTABLE run "${ZIMAGI_ARGS[@]}"
