# Generated by Django 2.1.3 on 2018-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
