# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('provider_type', models.CharField(editable=False, max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('state_config', systems.models.fields.EncryptedDataField(default={}, editable=False)),
                ('host', models.URLField(null=True)),
                ('port', models.IntegerField(default=5123)),
                ('user', models.CharField(default='admin', max_length=150)),
                ('token', systems.models.fields.EncryptedCharField(default='a11223344556677889900z', max_length=256)),
                ('repo', models.CharField(default='registry.hub.docker.com', max_length=1096)),
                ('base_image', models.CharField(default='zimagi/zimagi:latest', max_length=256)),
                ('runtime_image', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'environment',
                'verbose_name_plural': 'environments',
                'db_table': 'core_environment',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
