# Generated by Django 2.1.3 on 2019-02-23 14:14

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='token',
            field=systems.models.fields.EncryptedCharField(default='a11223344556677889900z', max_length=256),
        ),
    ]
