# Generated by Django 2.1.7 on 2019-04-02 00:43

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['name'], 'verbose_name': 'environment', 'verbose_name_plural': 'environments'},
        ),
        migrations.RemoveField(
            model_name='environment',
            name='type',
        ),
        migrations.AddField(
            model_name='environment',
            name='provider_type',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='environment',
            name='state_config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='variables',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
    ]
