# Generated by Django 2.2 on 2019-05-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='host',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='port',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='user',
        ),
    ]
