# Generated by Django 2.1.3 on 2018-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='environment',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
