# Generated by Django 2.1.3 on 2018-12-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20181124_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='host',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='port',
            field=models.IntegerField(default=5120),
        ),
        migrations.AddField(
            model_name='environment',
            name='token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
