# Generated by Django 3.2.5 on 2021-07-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='config',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='provider_type',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='state_config',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='variables',
        ),
    ]
