# Generated by Django 2.1.3 on 2019-02-24 15:23

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190223_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='config',
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
        migrations.AddField(
            model_name='environment',
            name='state_config',
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
        migrations.AddField(
            model_name='environment',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='variables',
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
    ]
