# Generated by Django 2.1.3 on 2018-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_auto_20181130_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='port',
            field=models.IntegerField(default=5123),
        ),
    ]
