# Generated by Django 3.2.5 on 2021-07-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_auto_20210711_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
