# Generated by Django 2.1.3 on 2018-12-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_auto_20181223_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
