# Generated by Django 2.1.3 on 2018-12-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0006_auto_20181227_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='token',
            field=models.CharField(default='a11223344556677889900z', max_length=40),
        ),
        migrations.AlterField(
            model_name='environment',
            name='user',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
