# Generated by Django 2.1.3 on 2018-12-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0007_auto_20181227_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='port',
            field=models.IntegerField(default=5123, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='user',
            field=models.CharField(default='admin', max_length=40, null=True),
        ),
    ]
