# Generated by Django 2.1.3 on 2018-12-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0009_auto_20181227_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=256)),
                ('value', models.TextField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='environment.Environment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('environment', 'name')},
        ),
    ]
