# Generated by Django 2.1.3 on 2018-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0010_auto_20181228_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
