# Generated by Django 2.1.3 on 2019-01-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0011_auto_20181229_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='config',
            name='environment',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
