# Generated by Django 2.1.3 on 2019-02-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systems.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environment', '0013_remove_environment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='image',
            field=models.CharField(default='cenv/cenv:latest', max_length=256),
        ),
        migrations.AddField(
            model_name='environment',
            name='repo',
            field=models.CharField(default='registry.hub.docker.com', max_length=1096),
        ),
        migrations.AddField(
            model_name='state',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='state',
            name='id',
            field=models.CharField(default=None, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='environment',
            name='port',
            field=models.IntegerField(default=5123),
        ),
        migrations.AlterField(
            model_name='environment',
            name='token',
            field=systems.models.EncryptedCharField(default='a11223344556677889900z', max_length=40),
        ),
        migrations.AlterField(
            model_name='state',
            name='value',
            field=systems.models.EncryptedTextField(null=True),
        ),
    ]
