# Generated by Django 2.1.3 on 2019-02-23 12:10

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('config', systems.models.fields.EncryptedDataField(default={})),
                ('type', models.CharField(max_length=128, null=True)),
                ('variables', systems.models.fields.EncryptedDataField(default={})),
                ('state_config', systems.models.fields.EncryptedDataField(default={})),
                ('mode', models.CharField(choices=[('ingress', 'ingress'), ('egress', 'egress')], default='ingress', max_length=10)),
                ('from_port', models.IntegerField(null=True)),
                ('to_port', models.IntegerField(null=True)),
                ('protocol', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], default='tcp', max_length=10)),
                ('cidrs', systems.models.fields.CSVField(null=True)),
                ('firewall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firewall.Firewall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='firewallrule',
            unique_together={('firewall', 'name')},
        ),
    ]
