# Generated by Django 2.1.3 on 2019-02-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='firewall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='firewall.Firewall'),
        ),
    ]
