# Generated by Django 2.1.3 on 2019-01-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='local_path',
        ),
        migrations.AddField(
            model_name='storage',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='zone',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
