# Generated by Django 2.1.3 on 2019-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190109_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='fs_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
