# Generated by Django 2.1.3 on 2019-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storage_fs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='config',
        ),
        migrations.AddField(
            model_name='storage',
            name='_config',
            field=models.TextField(db_column='config', null=True),
        ),
    ]
