# Generated by Django 2.1.3 on 2019-01-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20190119_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filesystems', to='environment.Environment'),
        ),
    ]
