# Generated by Django 2.1.3 on 2019-01-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20190127_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='fs_name',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='mount_options',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='remote_host',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='remote_path',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='zone',
        ),
        migrations.AlterField(
            model_name='storage',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='environment.Environment'),
        ),
    ]
