# Generated by Django 2.1.3 on 2019-01-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20190129_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('_config', models.TextField(db_column='config', null=True)),
                ('name', models.CharField(max_length=128)),
                ('remote_host', models.CharField(max_length=128, null=True)),
                ('remote_path', models.CharField(max_length=256, null=True)),
                ('mount_options', models.TextField(null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mounts', to='storage.Storage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='storagemount',
            unique_together={('storage', 'name')},
        ),
    ]
