# Generated by Django 2.1.3 on 2019-01-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20190127_0721'),
        ('storage', '0007_auto_20190129_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='network.Network'),
        ),
        migrations.AddField(
            model_name='storagemount',
            name='firewalls',
            field=models.ManyToManyField(related_name='mounts', to='network.Firewall'),
        ),
    ]
