# Generated by Django 2.1.3 on 2019-02-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_storagemount_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
        migrations.AddField(
            model_name='storagemount',
            name='_state',
            field=models.TextField(db_column='state', null=True),
        ),
    ]
