# Generated by Django 2.1.3 on 2019-02-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20190202_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='_config',
            field=models.TextField(db_column='config', default='{}'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='_state_config',
            field=models.TextField(db_column='state', default='{}'),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='_config',
            field=models.TextField(db_column='config', default='{}'),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='_state_config',
            field=models.TextField(db_column='state', default='{}'),
        ),
    ]
