# Generated by Django 2.1.3 on 2019-02-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20190205_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemount',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
