# Generated by Django 2.1.3 on 2019-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGroup',
            fields=[
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='config', to='config.ConfigGroup'),
        ),
    ]
