# Generated by Django 2.1.3 on 2019-01-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190121_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='config',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='config', to='config.ConfigGroup'),
        ),
    ]
