# Generated by Django 2.1.3 on 2019-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20190302_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='value_type',
            field=models.CharField(default='str', max_length=150),
        ),
    ]
