# Generated by Django 2.1.3 on 2019-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20190127_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='groups',
            field=models.ManyToManyField(related_name='config', to='config.ConfigGroup'),
        ),
    ]
