# Generated by Django 2.1.3 on 2019-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20190127_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='value',
            new_name='_value',
        ),
        migrations.AlterField(
            model_name='config',
            name='_value',
            field=models.TextField(db_column='value', null=True),
        ),
    ]
