# Generated by Django 2.1.3 on 2019-02-22 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systems.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0008_remove_config_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='config',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='config',
            name='groups',
            field=models.ManyToManyField(to='config.ConfigGroup'),
        ),
        migrations.AlterField(
            model_name='config',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='config',
            name='_value',
        ),
        migrations.RemoveField(
            model_name='config',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='config',
            name='user',
        ),
        migrations.AddField(
            model_name='config',
            name='value',
            field=systems.models.EncryptedTextField(null=True),
        ),
    ]
