# Generated by Django 2.1.3 on 2019-03-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_mount', '0002_auto_20190224_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemount',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='environment.Environment'),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='firewalls',
            field=models.ManyToManyField(related_name='storagemount_relation', to='firewall.Firewall'),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='storage.Storage'),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storagemount_relation', to='subnet.Subnet'),
        ),
    ]
