# Generated by Django 2.2 on 2019-05-20 10:49

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('host', models.URLField(null=True)),
                ('port', models.IntegerField(default=5123)),
                ('user', models.CharField(default='admin', max_length=150)),
                ('token', systems.models.fields.EncryptedCharField(default='a11223344556677889900z', max_length=256)),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='host_relation', to='environment.Environment')),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'hosts',
                'db_table': 'core_host',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('environment', 'name')},
            },
        ),
    ]
