# Generated by Django 3.2.5 on 2021-07-13 07:03

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('host', models.URLField()),
                ('port', models.IntegerField(default=5123)),
                ('user', models.CharField(default='admin', max_length=150)),
                ('token', systems.models.fields.EncryptedCharField(default='a11223344556677889900z', max_length=256)),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'hosts',
                'db_table': 'core_host',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
