# Generated by Django 3.2.10 on 2021-12-29 10:48

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='encryption_key',
            field=systems.models.fields.EncryptedCharField(max_length=256, null=True),
        ),
    ]
