# Generated by Django 3.2.10 on 2022-01-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_alter_host_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='port',
            new_name='command_port',
        ),
        migrations.AddField(
            model_name='host',
            name='data_port',
            field=models.IntegerField(default=5323),
        ),
    ]
