# Generated by Django 4.1.7 on 2023-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0002_alter_host_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="command_port",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="data_port",
            field=models.IntegerField(null=True),
        ),
    ]
