# Generated by Django 3.2.5 on 2021-07-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20190520_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='host',
            name='environment',
        ),
    ]
