# Generated by Django 4.1.13 on 2025-04-20 05:07

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0003_alter_host_command_port_alter_host_data_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="token",
            field=systems.models.fields.EncryptedCharField(
                default="123456789", max_length=256
            ),
        ),
    ]
