# Generated by Django 4.0.1 on 2022-02-05 00:57

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20220102_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='token',
            field=systems.models.fields.EncryptedCharField(default='uy5c8xiahf93j2pl8s00e6nb32h87dn3', max_length=256),
        ),
    ]
