# Generated by Django 4.0.7 on 2022-09-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_host_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
