# Generated by Django 4.1.13 on 2025-05-14 05:10

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("config", systems.models.fields.DictionaryField(default=dict)),
                ("provider_type", models.CharField(default="base", max_length=128)),
                (
                    "variables",
                    systems.models.fields.DictionaryField(default=dict, editable=False),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="group.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "db_table": "core_group",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
