# Generated by Django 4.1.2 on 2022-11-05 20:12

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="secrets",
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
    ]
