# Generated by Django 4.0.7 on 2022-09-26 08:38

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_config_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='config',
            field=systems.models.fields.DictionaryField(default=dict),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='group.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='provider_type',
            field=models.CharField(default='base', max_length=128),
        ),
    ]
