# Generated by Django 3.0 on 2020-02-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='group.Group')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='notification.Notification')),
            ],
            options={
                'verbose_name': 'notification group',
                'verbose_name_plural': 'notification groups',
                'db_table': 'core_notification_group',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='notificationsuccessgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='notificationsuccessgroup',
            name='notification',
        ),
        migrations.DeleteModel(
            name='NotificationAllGroup',
        ),
        migrations.DeleteModel(
            name='NotificationSuccessGroup',
        ),
    ]
