# Generated by Django 3.0 on 2020-02-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('notification', '0002_auto_20200202_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfailuregroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='group.Group'),
        ),
    ]
